
version: '3'
services:
  eureka-server:
    image: netflixoss/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  userservice:
    build:
      context: ./User Service
    image: userservice:latest
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Add other services like account-service, transaction-service, etc.
networks:
  mynetwork:
    driver: bridge
